version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asdasd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: asdasd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: asdasd
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - keycloak_network

  mongodb:
    image: mongo:latest
    container_name: keycloak_mongodb
    environment:
      MONGO_INITDB_DATABASE: keycloak-sessions
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - keycloak_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: keycloak_postgres_data
  mongodb_data:
    name: keycloak_mongodb_data
networks:
  keycloak_network:
    driver: bridge
